Download models from original sources (#8)
* Add mistral-7b-instruct f32 gguf model

* Download existing models from original sources

* Move chat.sh to repo's root

* Add basic config/input validation; remove hardcoded stack config

* Download models before first-use, to work around install hook's 10s timeout

---------

Signed-off-by: Farshid Tavakolizadeh <farshid.tavakolizadeh@canonical.com>

diff --git a/stacks/fallback-gpu/chat b/stacks/fallback-gpu/chat
--- a/stacks/fallback-gpu/chat
+++ b/stacks/fallback-gpu/chat
@@ -1,8 +1,21 @@
-#!/bin/bash -eux
+#!/bin/bash -eu
 
 ENGINE=$SNAP_COMPONENTS/mistral-inference
-MODEL_DIR=$SNAP_COMPONENTS/model
+MODEL=$SNAP_COMPONENTS/model
+
+if [ ! -d $MODEL ]; then
+    echo "Missing component: $MODEL"
+    exit 1
+fi
+
+$MODEL/init
+MODEL_FILES=$SNAP_USER_COMMON/model
+
+if [ ! -d $ENGINE ]; then
+    echo "Missing component: $ENGINE"
+    exit 1
+fi
 
 export PYTHONPATH=$ENGINE/lib/python3.12/site-packages
 
-exec $ENGINE/bin/mistral-chat $MODEL_DIR
+exec $ENGINE/bin/mistral-chat $MODEL_FILES
