Don't check models endpoint
Check error response

diff --git a/stacks/cpu/check-server b/stacks/cpu/check-server
--- a/stacks/cpu/check-server
+++ b/stacks/cpu/check-server
@@ -20,15 +20,29 @@ else
   exit 1
 fi
 
-served_model=$(wget http://localhost:8080/v1/models -O- 2>/dev/null | jq .data[0].id)
-if [[ "$served_model" == *"$model"* ]]; then
-  echo "Expected model is being served"
-else
-  echo "Models endpoint not returning expected model"
+#served_model=$(wget http://localhost:8080/v1/models -O- 2>/dev/null | jq .data[0].id)
+#if [[ "$served_model" == *"$model"* ]]; then
+#  echo "Expected model is being served"
+#else
+#  echo "Models endpoint not returning expected model"
+#  exit 1
+#fi
+
+api_response=$(\
+  wget http://localhost:8080/v1/completions \
+  --post-data='{"model": "", "prompt": "Say this is a test", "temperature": 0, "max_tokens": 1}' \
+  --content-on-error \
+  -O- \
+  2>/dev/null\
+)
+
+# Still starting up api_response = {"error":{"code":503,"message":"Loading model","type":"unavailable_error"}}
+error_text=$(echo $api_response | jq .error.message)
+if [ -n "${error_text}" ]; then
+  echo "Server is not ready: $error_text"
   exit 1
 fi
 
-api_response=$(wget http://localhost:8080/v1/completions --post-data='{"model": "", "prompt": "Say this is a test", "temperature": 0, "max_tokens": 1}' -O- 2>/dev/null)
 chat_text=$(echo $api_response | jq .choices[0].text)
 if [ -z "${chat_text}" ]; then
   echo "No response from completions api"
